# ui_components.py

import streamlit as st

def apply_styling():
    st.markdown(\"\"\"\n        <style>\n            .title-style { font-size:36px; font-weight:800; padding-bottom: 10px; color: #104547; }\n            .metric-style { font-size:24px; font-weight:bold; }\n            .card {\n                background: linear-gradient(145deg, #f8f9fa, #e6e9ef);\n                border-radius: 1.25rem;\n                padding: 1.5rem;\n                box-shadow: 0 6px 12px rgba(0,0,0,0.1);\n                transition: all 0.3s ease-in-out;\n            }\n            .card:hover {\n                transform: translateY(-3px);\n                box-shadow: 0 10px 20px rgba(0,0,0,0.15);\n            }\n            footer {visibility: hidden;}\n        </style>\n    \"\"\", unsafe_allow_html=True)

def show_logo_title():\n    st.image(\"https://i.imgur.com/fxyD8rF.png\", width=100)\n    st.markdown(\"<div class='title-style'>🚛 WasteTrack: Smart Waste Collection</div>\", unsafe_allow_html=True)

def show_sidebar(settings):\n    st.sidebar.markdown(\"## 👤 User Panel\")\n    st.sidebar.info(f\"👋 Logged in as: `{st.session_state.user}`\")\n\n    if st.session_state.user == \"admin\":\n        with st.sidebar.expander(\"⚙️ Admin Settings\", expanded=True):\n            from data_handler import save_settings\n            st.subheader(\"Manage Settings\")\n            new_vehicle = st.text_input(\"Add Vehicle\")\n            if st.button(\"Add Vehicle\") and new_vehicle:\n                settings[\"vehicles\"].append(new_vehicle)\n                save_settings(settings)\n                st.success(\"Vehicle added.\")\n\n            new_circuit = st.text_input(\"Add Collection Circuit\")\n            if st.button(\"Add Circuit\") and new_circuit:\n                settings[\"circuits\"].append(new_circuit)\n                save_settings(settings)\n                st.success(\"Circuit added.\")\n\n            new_employee = st.text_input(\"Add Employee\")\n            if st.button(\"Add Employee\") and new_employee:\n                settings[\"employees\"].append(new_employee)\n                save_settings(settings)\n                st.success(\"Employee added.\")\n\n            salary = st.number_input(\"Base Salary per Trip\", value=settings.get(\"salary\", 0.0))\n            bonus = st.number_input(\"Bonus per Trip\", value=settings.get(\"bonus_per_trip\", 0.0))\n            if st.button(\"💾 Save Pay Settings\"):\n                settings[\"salary\"] = salary\n                settings[\"bonus_per_trip\"] = bonus\n                save_settings(settings)\n                st.success(\"Pay settings saved.\")\n\n        with st.sidebar.expander(\"🔑 User Management\", expanded=False):\n            st.subheader(\"Create New Account\")\n            from auth import load_users, save_users\n            users = load_users()\n            new_user = st.text_input(\"New Username\")\n            new_pass = st.text_input(\"New Password\", type=\"password\")\n            if st.button(\"Create User\") and new_user and new_pass:\n                if new_user in users:\n                    st.warning(\"Username already exists.\")\n                else:\n                    import hashlib\n                    users[new_user] = hashlib.sha256(new_pass.encode()).hexdigest()\n                    save_users(users)\n                    st.success(\"User created successfully.\")"
